### ISSUE TITLE
General missing server commands

### ISSUE THREAD

**Issue by fucksophie** [rdebath/mcchost#1]
I have no clue how to give myself Admin permissions, and how to lock people out of using /kick.. I think it should be by default only executable by ops

**Comment by rdebath** [comment]
Good point,

In the version you have there isn't any way to give a user "OP", the permissions are based entirely on the remote IP address. The user is the OP if it's localhost or an address specified by the `Localnet` option in server.ini for example: `Localnet = 192.168.0.0/16`.

I'm adding a `UserPerm` option to the `user/<name>.ini` file to allow for that and "ban".

That'll do for now; but I really need to think how the perms should work.

PS: and yes kick needs "is_admin".

**Comment by rdebath** [comment]
Okay, there's some code there for minimal user permissions.
`/setrank` command should allow you to set yourself if you're connected from localhost eg with [mini_chat](https://github.com/rdebath/mc/blob/master/extras/mini_chat.c) or change the user ini file to have `UserPerm=1`

`/kick`, `/ban` and `/unban` seem to work nicely.

**Comment by fucksophie** [comment]
I think I'll expand this issue to include some more missing very important command limiting and other imporant things such as that.

Issues I found:
1. /cuboid, /replace or /replaceall aren't limited in any way, in the case that a malicious actor would join the game and just /replace'd everything to lava or something like that.
2. /setmain to set the world that a person would join in by default (admin only)
3. /nick, and probably /title

**Comment by rdebath** [comment]
2. Main is set by the `main` item in server.ini. This can be set in game with `/set server main [levelname]`. If the level doesn't exist it'll be created on connect.

I'll add an alias in the `/main` command too I think.

**Comment by rdebath** [comment]
Okay those seem to be working. Do you have other priority preferences ?

**Comment by fucksophie** [comment]
Yeah, the cuboid limit which I mentioned in my last comment.

**Comment by rdebath** [comment]
I guess you mean a limit of the number of blocks a guest is allowed to set in a single command.
I've added a simple variable for the default user type, but I'm not sure how useful it is. 
The way I see it is that if it's below a couple of hundred you might as well just disable `/cuboid` completely but if it's anywhere near that high it increases the block rate immensely.
I suppose it might help a touch against kiddies who only know a command or two. 

```
$ cat cmdset.ini
[cmdlimits]
MaxUserBlock = 400
$ 
```
